# Generated by Django 4.2.4 on 2023-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_column='fullname', max_length=200)),
                ('email', models.EmailField(db_column='email', max_length=200, unique=True)),
                ('password', models.CharField(db_column='password', max_length=200)),
            ],
        ),
    ]
